# Generated by Django 4.1 on 2022-08-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('voluntario_Id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('habilit_plataf', models.CharField(blank=True, choices=[('hab', 'si'), ('no', 'no'), ('', 'ninguno')], default='', max_length=14)),
                ('habilit_microf', models.CharField(blank=True, choices=[('hab', 'si'), ('no', 'no'), ('', 'ninguno')], default='hab', max_length=14)),
                ('habilit_Zoom', models.CharField(blank=True, choices=[('hab', 'si'), ('no', 'no'), ('', 'ninguno')], default='', max_length=14)),
                ('habilit_acomod', models.CharField(blank=True, choices=[('hab', 'si'), ('no', 'no'), ('', 'ninguno')], default='hab', max_length=14)),
                ('habilit_presid', models.CharField(blank=True, choices=[('hab', 'si'), ('no', 'no'), ('', 'ninguno')], default='', max_length=14)),
                ('habilit_lector', models.CharField(blank=True, choices=[('hab', 'si'), ('no', 'no'), ('', 'ninguno')], default='', max_length=14)),
                ('privilegio', models.CharField(blank=True, choices=[('ministerial', 'ministerial'), ('anciano', 'anciano'), ('', 'ninguno')], default='', max_length=12)),
            ],
            options={
                'ordering': ['nombres', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('Zoom_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('voluntario_Id', models.ForeignKey(limit_choices_to={'habilit_Zoom': 'hab'}, on_delete=django.db.models.deletion.CASCADE, to='funciones.voluntario')),
            ],
            options={
                'ordering': ['fecha', 'voluntario_Id'],
            },
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('presid_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('voluntario_Id', models.ForeignKey(limit_choices_to={'habilit_presid': 'hab'}, on_delete=django.db.models.deletion.CASCADE, to='funciones.voluntario')),
            ],
            options={
                'ordering': ['fecha', 'voluntario_Id'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('plataf_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('voluntario_Id', models.ForeignKey(limit_choices_to={'habilit_plataf': 'hab'}, on_delete=django.db.models.deletion.CASCADE, to='funciones.voluntario')),
            ],
            options={
                'ordering': ['fecha', 'voluntario_Id'],
            },
        ),
        migrations.CreateModel(
            name='Microfono',
            fields=[
                ('microfono_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('voluntario_Id', models.ForeignKey(limit_choices_to={'habilit_microf': 'hab'}, on_delete=django.db.models.deletion.CASCADE, to='funciones.voluntario')),
            ],
            options={
                'ordering': ['fecha', 'voluntario_Id'],
            },
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('lector_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('voluntario_Id', models.ForeignKey(limit_choices_to={'habilit_lector': 'hab'}, on_delete=django.db.models.deletion.CASCADE, to='funciones.voluntario')),
            ],
            options={
                'ordering': ['fecha', 'voluntario_Id'],
            },
        ),
        migrations.CreateModel(
            name='Acomodador',
            fields=[
                ('acomodador_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True)),
                ('voluntario_Id', models.ForeignKey(limit_choices_to={'habilit_acomod': 'hab'}, on_delete=django.db.models.deletion.CASCADE, to='funciones.voluntario')),
            ],
            options={
                'ordering': ['fecha', 'voluntario_Id'],
            },
        ),
    ]
