# Generated by Django 4.1 on 2022-08-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acomodador',
            options={'ordering': ['fecha']},
        ),
        migrations.AlterModelOptions(
            name='microfono',
            options={'ordering': ['fecha']},
        ),
        migrations.RenameField(
            model_name='acomodador',
            old_name='voluntario_Id',
            new_name='voluntarioDos',
        ),
        migrations.RenameField(
            model_name='microfono',
            old_name='voluntario_Id',
            new_name='voluntarioDos',
        ),
        migrations.AddField(
            model_name='acomodador',
            name='voluntarioUno',
            field=models.ForeignKey(limit_choices_to={'habilit_acomod': 'hab'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acomodadors', to='funciones.voluntario'),
        ),
        migrations.AddField(
            model_name='microfono',
            name='voluntarioUno',
            field=models.ForeignKey(limit_choices_to={'habilit_microf': 'hab'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Microfonos', to='funciones.voluntario'),
        ),
    ]
